spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        #acknowledge-mode: manual #设置确认模式手工确认
        concurrency: 3 #消费者最小数量
        max-concurrency: 10 # 消费者最大数量
    #虚拟host 可以不设置,使用server默认host
 #   virtual-host: JCcccHost

  #消息确认配置项

  #确认消息已发送到交换机(Exchange)
  publisher-confirms: true
  #确认消息已发送到队列(Queue)
  publisher-returns: true